services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_USER: test_user
      MYSQL_DATABASE: test_database
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: supersecret
    ports:
      - 9306:3306

  node-red:
    image: nodered/node-red
    ports:
      - 9880:1880
    volumes:
      - ./data/node-red:/data
